name: ${COMPOSE_PROJECT_NAME}

services:
  mysql:
    image: mysql:8.4
    container_name: pehlione-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    command:
      [
        "mysqld",
        "--mysql-native-password=ON",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./infra/mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD} --silent",
        ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s
    networks:
      - pehlione_network

  redis:
    image: redis:7.4-alpine
    container_name: pehlione-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - pehlione_network

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: pehlione-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - pehlione_network

volumes:
  mysql_data:
  redis_data:

networks:
  pehlione_network:
    driver: bridge
