export enum Role {
  ADMIN = "ADMIN",
  USER = "USER",
}

export enum MembershipTier {
  BRONZE = "BRONZE",
  SILVER = "SILVER",
  GOLD = "GOLD",
}

export enum MembershipStatus {
  ACTIVE = "ACTIVE",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
}

export enum AuditAction {
  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",
  USER_DELETED = "USER_DELETED",
  LOGIN_SUCCEEDED = "LOGIN_SUCCEEDED",
  LOGIN_FAILED = "LOGIN_FAILED",
  LOGOUT_SUCCEEDED = "LOGOUT_SUCCEEDED",
  PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED = "PASSWORD_RESET_COMPLETED",
  EMAIL_VERIFICATION_SENT = "EMAIL_VERIFICATION_SENT",
  EMAIL_VERIFIED = "EMAIL_VERIFIED",
  MEMBERSHIP_TIER_UPDATED = "MEMBERSHIP_TIER_UPDATED",
  ROLE_UPDATED = "ROLE_UPDATED",
  SESSION_REVOKED = "SESSION_REVOKED",
  ACCOUNT_DISABLED = "ACCOUNT_DISABLED",
  ACCOUNT_ENABLED = "ACCOUNT_ENABLED",
  PASSWORD_CHANGED = "PASSWORD_CHANGED",
}
